Add resource_estimate to qss
SupertechLabs/qiskit-superstaq pull request #181
Opened 2022-06-26 21:36 UTC by paaige

2022-06-26 22:08 UTC, vtomole commented on qiskit_superstaq/superstaq_provider.py
> +    ) -> dict:
We want to use [typing.Dict](https://stackoverflow.com/a/37087556/5716192) so that we can be really specific about the types of this `Dict`

2022-06-26 22:08 UTC, vtomole commented on qiskit_superstaq/superstaq_provider_test.py
> +    resource_estimate = 0.50
I though Resource estimate was a `Dataclass`, not a `float`.

2022-06-27 15:26 UTC, singular-value requested changes
I think one of the things going on right now is that the draft code in web/server.py just returns a str() of the ResourceEstimate.

There should be a better way to serialize objects. Perhaps https://stackoverflow.com/a/54120624.

2022-06-27 15:26 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +            ResourceEstimate object containing gate count, critical path length, and error estimate.
```suggestion
            ResourceEstimate object containing resource costs (after compilation) for running circuit(s) on target.
```

2022-06-27 15:26 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +    ) -> dict:
and in fact, the return type here should be `applications_superstaq.ResourceEstimate` right?

2022-06-27 15:26 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +        return json_dict["resource_estimates"]
there should be code that converts the json_dict into a `ResourceEstimate` object.

See aqt_compile below, which does something similar.

2022-06-27 15:26 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +            ResourceEstimate object containing gate count, critical path length, and error estimate.
^ so that we don't have to update this docstring anytime we edit the `ResourceEstimate` spec

2022-06-28 18:17 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +    ) -> dict:
```suggestion
    ) -> Union[ResourceEstimate, List[ResourceEstimate]]:
```

2022-06-28 18:20 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +    ) -> dict:
Can model https://github.com/Qiskit/qiskit-terra/blob/10822404936e98df01f2975ef43b8378006621ba/qiskit/compiler/transpiler.py#L256 for forking off return type based on input type

2022-07-06 19:55 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +        # Type must be specified due to mypy issue: https://github.com/python/mypy/issues/6898
follow simple type stuff in css

2022-07-07 03:28 UTC, vtomole commented
Fix the conflict.

2022-07-07 03:31 UTC, vtomole approved these changes
LGTM

2022-07-07 03:41 UTC, merged