Support compiling multiple circuits for AQT
SupertechLabs/qiskit-superstaq pull request #30
Opened 2021-08-27 21:08 UTC by singular-value

2021-08-30 20:53 UTC, singular-value commented on qiskit_superstaq/aqt.py
> +    compiled_circuits = [qiskit.QuantumCircuit.from_qasm_str(q) for q in json_dict["qasm_strs"]]
(outdated since new API will always return "qasm_strs")

2021-08-30 20:53 UTC, singular-value commented on qiskit_superstaq/aqt.py
> +    if "qasm_str" in json_dict:
resolving since server now always returns "qasm_strs"

2021-08-30 20:54 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +        if isinstance(circuits, qiskit.QuantumCircuit):
only one /aqt_compile endpoint now; it always takes a list of circuits

2021-08-30 20:55 UTC, singular-value reviewed
Ready for review again.

Let's pair program on the versioning stuff tomorrow btw.

2021-09-01 17:40 UTC, vtomole requested changes
One small change then LGTM

2021-09-01 17:40 UTC, vtomole commented on qiskit_superstaq/aqt.py
> +    def __repr__(self) -> str:
Let's do 
```
  def __repr__(self) -> str:
        if hasattr(self, "circuit"):
            return f"AQTCompilerOutput({self.circuit!r}, {self.seq})"
        return f"AQTCompilerOutput({self.circuits!r}, {self.seq})"

```

2021-09-01 19:33 UTC, singular-value commented on qiskit_superstaq/aqt.py
> +    def __repr__(self) -> str:
ah good

2021-09-01 19:35 UTC, singular-value commented on qiskit_superstaq/aqt.py
> +    def __repr__(self) -> str:
done

2021-09-01 19:46 UTC, vtomole approved these changes

2021-09-01 22:29 UTC, merged