Add qscout_tutorial.ipynb to qiskit-superstaq/examples
SupertechLabs/qiskit-superstaq pull request #317
Opened 2023-02-14 16:39 UTC by hallben4

2023-02-14 17:35 UTC, singular-value requested changes
Thanks. A few requests:
(1) Please remove the cirq examples/imports from the notebook. (And correspondingly, remove the qiskit examples/imports from the css notebook)
(2) Since there is already a qscout_compile.ipynb notebook, I think it would make sense to combine those two. (Ditto in css)
(3) Looks like the notebook is failing tests. Please check out the output and fix.

2023-02-15 18:14 UTC, pnoell commented
Will add MPL drawer to example requirements and remove #!pip install in notebook

2023-02-15 18:28 UTC, richrines1 commented on examples/qscout_tutorial.ipynb
> +    "token = \"1f59b6240f2b6c9b007b4cfe41b8f468713b95dedcf9b796a825edcf64f54e53\"\n",
oops - need to change this token

2023-02-24 18:52 UTC, hallben4 commented
The notebook keeps failing because the it can't find the superstaq token. But we're not supposed to put the token on github. How do we resolve this?

2023-03-07 17:33 UTC, richrines1 commented on examples/qscout_tutorial.ipynb
> +    "! pip install pylatexenc"
as per the box above, these should be commented:
```suggestion
    "# ! pip install qiskit-superstaq\n",
    "# Required for pretty-printing circuit diagrams:\n",
    "# ! pip install pylatexenc"
```
(also removed typing-extensions, as it's already required by gss)

the notebook should also be re-run to remove the output block

2023-03-07 17:33 UTC, richrines1 commented on examples/qscout_tutorial.ipynb
> +      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
re-run or fix to get rid of this error

2023-03-07 17:33 UTC, richrines1 commented on examples/qscout_tutorial.ipynb
> +    "# os.environ[\"SUPERSTAQ_API_KEY\"] = token"
maybe add a note saying to either uncomment these and add a token, or set the SUPERSTAQ_API_KEY variable in your local env

2023-03-24 16:45 UTC, richrines1 commented
@hallben4 do you mind reopening this in https://github.com/SupertechLabs/client-superstaq/ (reach out if you need help)

2023-03-29 19:33 UTC, closed without merging