Converters
SupertechLabs/qiskit-superstaq pull request #37
Opened 2021-09-02 19:19 UTC by richrines1

* adds functions to support circuit (de)serialization using `qpy`
* server requests will be modified to use converters.(de)serialize_circuits in a separate PR

2021-09-02 19:22 UTC, singular-value commented on qiskit_superstaq/converters.py
> +    return codecs.decode(str_data.encode(), "base64")
Was the plan to have this stuff in applications-superstaq to factor out common client code?

You already have https://github.com/SupertechLabs/applications-superstaq/pull/5/files

2021-09-02 19:24 UTC, singular-value requested changes

2021-09-02 19:24 UTC, singular-value commented on qiskit_superstaq/converters.py
> +    """Serialize QuantumCircuits into a single string
```suggestion
    """Serialize QuantumCircuit(s) into a single string
```

2021-09-02 20:06 UTC, richrines1 commented on qiskit_superstaq/converters.py
> +    return codecs.decode(str_data.encode(), "base64")
yeah these and the following two functions should be common among the clients so I was assuming they would ultimately be factored out. For the time being I wasn't sure if avoiding duplicating 4 one-liners was worth adding the applications-superstaq dependency, but if we know we're going to eventually maybe that's silly

2021-09-02 20:07 UTC, singular-value commented on qiskit_superstaq/converters.py
> +    return codecs.decode(str_data.encode(), "base64")
Yeah we're going to do it eventually (in fact soon, since we need to bring the finance/logistics endpoints to qiskit-superstaq), so might as well do it here.

2021-09-02 20:31 UTC, richrines1 commented on qiskit_superstaq/converters.py
> +    return codecs.decode(str_data.encode(), "base64")
makes sense, I'll update.

2021-09-02 22:36 UTC, vtomole approved these changes
LGTM

2021-09-02 22:36 UTC, vtomole commented on requirements.txt
> +applications-superstaq==0.0.3
```suggestion
applications-superstaq==0.0.4
```

2021-09-02 22:37 UTC, vtomole reviewed
Nit: Maybe rename `converters.py` to `serialization.py`?

2021-09-02 22:42 UTC, richrines1 commented
@vtomole I agree, that's better. it should also be changed in applications_superstaq

2021-09-08 15:38 UTC, singular-value requested changes

2021-09-08 15:38 UTC, singular-value commented on requirements.txt
> +applications-superstaq==0.0.4
Let's do >= like in https://github.com/SupertechLabs/cirq-superstaq/blob/main/requirements.txt

2021-09-09 03:37 UTC, singular-value submitted a review, later dismissed

2021-09-09 14:56 UTC, singular-value approved these changes
lg

2021-09-09 15:12 UTC, merged