Change `backends` method to request from API endpoint
SupertechLabs/qiskit-superstaq pull request #57
Opened 2021-11-01 23:00 UTC by dowusu-antwi

Fixes #55.

2021-11-09 16:35 UTC, vtomole requested changes

2021-11-09 16:35 UTC, vtomole commented on qiskit_superstaq/superstaq_provider.py
> +        res = requests.get(
Since we are already here, move this `applications-superstaq`

2021-12-30 02:41 UTC, dowusu-antwi commented on qiskit_superstaq/superstaq_provider.py
> +        res = requests.get(
This has been in queue for a while, so to review the situation:

1. We had a new server endpoint, `GetBackends`.
2. We wanted the `qss` backends method to use this new endpoint directly (via SuperstaQ), so we made the necessary changes.
3. Victory pointed out that we now want `GetBackends` to be accessed via `applications-superstaq`(which at the time we were adding functionality to).

In a nutshell, this will be subsumed by bringing `qss` up to par, i.e., building up `superstaq_provider.py` to make full use of SuperstaQ via `applications-superstaq`.

(These notes are from making minor local changes to try and spin up (not yet passing all the tests, for agility's sake) a version that uses `get_backends` from `applications_superstaq` -- perhaps we can use this PR to `qss` parity.)

2021-12-30 02:42 UTC, dowusu-antwi commented
This has been in queue for a while, so to review the situation:

1. We had a new server endpoint, `GetBackends`.
2. We wanted the `qss` backends method to use this new endpoint directly (via SuperstaQ), so we made the necessary changes.
3. Victory pointed out that we now want `GetBackends` to be accessed via `applications-superstaq`(which at the time we were adding functionality to).

In a nutshell, this will be subsumed by bringing `qss` up to par, i.e., building up `superstaq_provider.py` to make full use of SuperstaQ via `applications-superstaq`.

(These notes are from making minor local changes to try and spin up (not yet passing all the tests, for agility's sake) a version that uses `get_backends` from `applications_superstaq` -- perhaps we can use this PR to `qss` parity.)

2022-01-11 17:57 UTC, dowusu-antwi commented on qiskit_superstaq/superstaq_provider.py
> +        res = requests.get(
Fixed (`get_backends` called from `applications-superstaq`).

2022-01-11 19:36 UTC, singular-value approved these changes
lgtm
added balance integration test in #77

2022-01-11 19:36 UTC, singular-value commented on qiskit_superstaq/superstaq_provider_test.py
> +@patch.dict(os.environ, {"SUPERSTAQ_API_KEY": ""})
Just filed https://github.com/SupertechLabs/qiskit-superstaq/issues/76 for treatment in a separate issue.

2022-01-11 19:51 UTC, richrines1 commented on qiskit_superstaq/superstaq_provider.py
> +    def get_balance(self, pretty_output: bool = True) -> Union[str, float]:
isn't `get_balance` already inherited from `UserConfig`?

2022-01-11 20:10 UTC, dowusu-antwi commented on qiskit_superstaq/superstaq_provider.py
> +    def get_balance(self, pretty_output: bool = True) -> Union[str, float]:
Yes, thanks -- I keep forgetting about `UserConfig`! Fixed.

2022-01-11 20:14 UTC, richrines1 submitted a review, later dismissed
lgtm

2022-01-12 15:09 UTC, dowusu-antwi commented
Updated notebook to show parity:

![qss-parity](https://user-images.githubusercontent.com/18367737/149166625-3be07e10-4f32-4ecd-a27c-798227f6ffb1.png)

2022-01-12 15:30 UTC, vtomole commented
So as of now, there is no service call in css that's not in qss?

2022-01-12 15:37 UTC, dowusu-antwi commented
> So as of now, there is no service call in css that's not in qss?

Good question. E.g., we currently submit jobs and get counts with:

https://github.com/SupertechLabs/qiskit-superstaq/blob/6adfe257382814a2eded33451ebd46f9faaa761a/examples/hello_qiskit_superstaq.py#L30-L40

Do we want to also have a `create_job` and `get_counts` like in the `css` service calls? In that case, I can add those. Also, I recall @singular-value saying he's adding `ibmq_compile` in another PR, but I may be misremembering and can add that here as well.

2022-01-12 15:50 UTC, vtomole commented
From your screenshot, it looks like `get_counts` is the same. We can leave the implementation of `create_job` because `backend.run` is the spirit of the `qiskit` interface.

2022-01-12 17:37 UTC, singular-value commented on qiskit_superstaq/superstaq_provider.py
> +    def get_balance(self, pretty_output: bool = True) -> Union[str, float]:
Whoa nice!

2022-01-12 17:37 UTC, singular-value commented
> Do we want to also have a `create_job` and `get_counts` like in the `css` service calls? In that case, I can add those. Also, I recall @singular-value saying he's adding `ibmq_compile` in another PR, but I may be misremembering and can add that here as well.

Yup, I'm working on adding `ibmq_compile` in another PR.

2022-01-12 17:42 UTC, vtomole requested changes
Add a [similar](https://github.com/SupertechLabs/cirq-superstaq/blob/70bdff40ed54d97dd90f8794db0cb3b2fa246d5d/cirq_superstaq/daily_integration_test.py#L64) integration test.

2022-01-13 17:50 UTC, dowusu-antwi commented
> Add a [similar](https://github.com/SupertechLabs/cirq-superstaq/blob/70bdff40ed54d97dd90f8794db0cb3b2fa246d5d/cirq_superstaq/daily_integration_test.py#L64) integration test.

Done:
![daily-integration-check](https://user-images.githubusercontent.com/18367737/149382640-ed1305cd-7df4-41ea-945c-604587ee70a1.png)

2022-01-13 17:55 UTC, vtomole commented
If you want to merge this now, change the title of this PR to be more specific.

2022-01-14 18:26 UTC, vtomole approved these changes
LGTM

2022-01-14 18:40 UTC, merged