Adds client-side functionality for setting IBMQ token
SupertechLabs/qiskit-superstaq pull request #74
Opened 2022-01-07 21:45 UTC by dowusu-antwi

Inherits functionality for IBMQ token endpoint from up-to-date `applications-superstaq`:

![qss-success-token](https://user-images.githubusercontent.com/18367737/148611140-19cf75b8-6494-4bc8-8006-fd3607eeeab8.png)

2022-01-07 21:45 UTC, dowusu-antwi commented
Invalid token returns expected error:

![qss-fail-token](https://user-images.githubusercontent.com/18367737/148611455-b72ef358-3214-4787-a769-6a67c86221d6.png)

2022-01-07 21:57 UTC, vtomole commented
Have you pushed this code? The diff shows only a `requirements.txt` change.

2022-01-07 22:00 UTC, dowusu-antwi commented
> Have you pushed this code? The diff shows only a `requirements.txt` change.

Yes -- this actually inherits `ibmq_set_token` from `UserConfig`.

2022-01-07 22:01 UTC, vtomole requested changes
How can the `your token failed to update` error be triggered? Let's add a `daily_integration_test` for this API.

2022-01-07 23:26 UTC, dowusu-antwi commented
> How can the `your token failed to update` error be triggered?

I think this would only be triggered by passing a valid token followed by a failed database commit (i.e., `web.db.session.commit()` fails after token validation). I'm not sure when / if this could happen, but it matches what we do with the `aqt_configs` endpoint.

> Let's add a `daily_integration_test` for this API.

Adding an IBMQ token similar to in
https://github.com/SupertechLabs/qiskit-superstaq/blob/e22dbf31a17ad04b8b5b0892006d81058635b6f2/.github/workflows/daily-integration-check.yml#L12-L13
should allow the added test to pass.

2022-01-07 23:30 UTC, vtomole commented
>  think this would only be triggered by passing a valid token followed by a failed database commit

Okay, then this falls under the bucket of [can't test](https://en.wikipedia.org/wiki/Defensive_programming). We can leave as-is.

2022-01-07 23:35 UTC, vtomole commented on qiskit_superstaq/daily_integration_test.py
> +    assert provider.ibmq_set_token(ibmq_token) == "Your IBM Q account token has been updated"
Does this pass locally for you? I don't see `ibmq_set_token` in the `SuperstaQProvider` class?

2022-01-07 23:38 UTC, dowusu-antwi commented on qiskit_superstaq/daily_integration_test.py
> +    assert provider.ibmq_set_token(ibmq_token) == "Your IBM Q account token has been updated"
Yep, `/check/all` passes locally (see https://github.com/SupertechLabs/qiskit-superstaq/pull/74#issuecomment-1007770690) -- although since it's an integration test, I'm actually not sure exactly how communication with the server is handled locally, as opposed to the GitHub tests below.

2022-01-07 23:43 UTC, vtomole commented on qiskit_superstaq/daily_integration_test.py
> +    assert provider.ibmq_set_token(ibmq_token) == "Your IBM Q account token has been updated"
Oh i missed that.

2022-01-08 00:14 UTC, vtomole approved these changes
LGTM!

2022-01-08 00:16 UTC, merged