`neutral_atom_compile`
SupertechLabs/qiskit-superstaq pull request #83
Opened 2022-01-14 23:03 UTC by dowusu-antwi

Adds method for `neutral_atom_compile`.

2022-01-14 23:38 UTC, richrines1 commented on qiskit_superstaq/superstaq_provider.py
> +    ) -> Any:
can we avoid using `Any` here? e.g.
```suggestion
    ) -> Union[qiskit.QuantumCircuit, List[qiskit.QuantumCircuit]]:
```
(if so it should probably be changed in cirq-superstaq as well)

2022-01-14 23:39 UTC, vtomole requested changes
Add a notebook similar to https://github.com/SupertechLabs/cirq-superstaq/blob/main/examples/neutral_atom_compile.ipynb

2022-01-18 19:26 UTC, dowusu-antwi commented on pulse-requirements.txt
> +pulser~=0.1.1
These requirements should be installed before running the example notebook. (If anyone has a better name for the new requirements file let me know, maybe something like `client-requirements.txt`?)

2022-01-19 21:56 UTC, richrines1 commented on pulse-requirements.txt
> +pulser~=0.1.1
are these only required for `neutral_atom_compile()`? if so what about `neutral-atom-requirements.txt`?

2022-01-19 22:07 UTC, dowusu-antwi commented on pulse-requirements.txt
> +pulser~=0.1.1
That sounds good to me -- done.

2022-01-19 22:56 UTC, vtomole requested changes
Minor nit then LGTM

2022-01-19 22:56 UTC, vtomole commented on qiskit_superstaq/superstaq_provider.py
> +        Pulse must be installed for returned object to correctly deserialize to a pulse schedule.
```suggestion
        Pulser must be installed for returned object to correctly deserialize to a pulse schedule.
```

2022-01-19 22:59 UTC, vtomole submitted a review, later dismissed
LGTM

2022-01-19 23:01 UTC, vtomole reviewed
Maybe for another PR or we can do it here: Let the user know that neutral_atom_requirements.txt` exists. Should we actually have it in the error message as well?

2022-01-19 23:02 UTC, vtomole commented
```python
applications_superstaq.SuperstaQModuleNotFoundException(
                name=str(e.name), context="neutral_atom_compile"
            )
```
Would give
`This module wasn't found. Please pip install neutral_atom_requirements.txt` and you'll be good to go`

2022-01-19 23:04 UTC, vtomole commented
That might be overkill. We are good with just having it in the README.

2022-01-19 23:13 UTC, dowusu-antwi commented
Added README (ready for re-review, @vtomole @richrines1).

2022-01-19 23:14 UTC, vtomole approved these changes
LGTM

2022-01-19 23:15 UTC, merged