Update qiskit_example (multiple circuits, add comments)
SupertechLabs/qiskit-superstaq pull request #9
Opened 2021-08-02 03:46 UTC by rohansk1

Resolves #5, #8

2021-08-02 04:14 UTC, rohansk1 commented
Keeping this as a draft because when I run `examples/qiskit-example.py` locally, I get the following error: 

`  File "examples/qiskit_example.py", line 8, in <module>
    superstaq = qss.superstaq_provider.SuperstaQProvider(token)
AttributeError: module 'qiskit_superstaq' has no attribute 'superstaq_provider'`

2021-08-02 04:22 UTC, rohansk1 commented
Also, can we rename this file to `qiskit_superstaq_example.py` or `qss_example.py`? The name can be confusing since it doesn't mention SuperstaQ and implies it demonstrates qiskit itself.

2021-08-02 16:46 UTC, vtomole commented
> Also, can we rename this file to qiskit_superstaq_example.py or qss_example.py? The name can be confusing since it doesn't mention SuperstaQ and implies it demonstrates qiskit itself. To make it consistent with cirq_superstaq we could call it qiskit_superstaq_example.py

All files in `examples` here will be `qiskit_superstaq_examples`; so the name is vague right now. Let's call this file `multiple_circuits.py`.  We can move the original bell circuit example to a new file `hello_qiskit_superstaq.py`

2021-08-02 16:52 UTC, vtomole commented
> Is this reproducible on your computer? Any ideas on how to solve it?

Pip install qiskit-superstaq like so: `pip install -e .`

BTW i get this error 

```
(venv1) (base) vtomole@vtomole:~/qiskit-superstaq/examples$ python qiskit_example.py 
Traceback (most recent call last):
  File "qiskit_example.py", line 34, in <module>
    print(job.result().get_counts())
  File "/home/vtomole/qiskit-superstaq/qiskit_superstaq/superstaq_job.py", line 93, in result
    {"success": True, "shots": result["shots"], "data": {"counts": result["samples"]}}
KeyError: 'shots'
(venv1) (base) vtomole@vtomole:~/qiskit-superstaq/examples$ 
```

2021-08-03 05:27 UTC, rohansk1 commented
@vtomole Everything works on my machine now. Only issue is the recurrent pesky InsecureRequestWarnings:

`InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings`

But I've filed an issue for that and will create a new PR for it.

2021-08-03 23:16 UTC, singular-value reviewed
lgtm from skim, deferring to @vtomole

2021-08-06 15:39 UTC, vtomole requested changes

2021-08-06 15:39 UTC, vtomole commented on examples/multiple_circuits.py
> +"""
Replace `"""` with `#`

2021-08-06 15:39 UTC, vtomole commented on examples/multiple_circuits.py
> +import qiskit
Add doc at top of file as to what this file does. Similar to https://github.com/quantumlib/Cirq/blob/c3f9a5d6d4d539fc9de737e46e9e1d728ef27379/examples/hello_qubit.py#L1

2021-08-06 15:39 UTC, vtomole commented on examples/hello_qiskit_superstaq.py
> +import qiskit
Add doc at top of file as to what this file does. Similar to https://github.com/quantumlib/Cirq/blob/c3f9a5d6d4d539fc9de737e46e9e1d728ef27379/examples/hello_qubit.py#L1

2021-08-11 16:22 UTC, vtomole requested changes

2021-08-11 16:22 UTC, vtomole commented on examples/multiple_circuits.py
> +[{'00': 48, '11': 52}, {'000': 48, '111': 52}]
It's so weird how all these results are the same (48, 52). There has to be a bug somewhere in either `qiksit-superstaq` or the backend. Something to look into, but not here.

2021-08-11 16:22 UTC, vtomole commented on examples/hello_qiskit_superstaq.py
> +print(job.status().value)
I forget: What changes did we make so that we have to call `.value` on jobstatus?

2021-08-12 02:21 UTC, rohansk1 commented on examples/multiple_circuits.py
> +[{'00': 48, '11': 52}, {'000': 48, '111': 52}]
It was just a coincidence. I've seen them be different. I'll change them in the example file to indicate they can be different.

2021-08-12 02:29 UTC, rohansk1 commented on examples/hello_qiskit_superstaq.py
> +print(job.status().value)
Nothing changed, but I think in the example file it's nicer to print "job has successfully run" rather than JobStatus.DONE.

2021-08-12 02:30 UTC, vtomole commented on examples/hello_qiskit_superstaq.py
> +print(job.status().value)
👍

2021-08-12 02:31 UTC, vtomole commented on examples/multiple_circuits.py
> +[{'00': 48, '11': 52}, {'000': 48, '111': 52}]
Okay change them then this PR is good to me.

2021-08-12 02:42 UTC, vtomole approved these changes
LGTM

2021-08-13 04:23 UTC, singular-value commented
@rohansk1 merge in?

2021-08-13 14:00 UTC, merged